
// states
CREATE  TABLE IF NOT EXISTS `storefront`.`states`(
ID INT NOT NULL CHECK(ID > 0),
stateName VARCHAR(20),
PRIMARY KEY(ID)
);

//cities
CREATE  TABLE IF NOT EXISTS `storefront`.`cities`(
ID INT NOT NULL CHECK(ID > 0),
cityName VARCHAR(20),
PRIMARY KEY(ID)
);

//zips
CREATE  TABLE IF NOT EXISTS `storefront`.`zips`(
ID INT NOT NULL CHECK(ID > 0),
zip CHAR(6) CHECK(zip like '%[^0-9]%'),
PRIMARY KEY(ID)
);

//zipcity
CREATE  TABLE IF NOT EXISTS `storefront`.`zipCity`(
ID INT NOT NULL CHECK(ID > 0),
zipId INT NOT NULL CHECK(ID > 0),
cityId INT NOT NULL CHECK(ID > 0),
PRIMARY KEY(ID),
FOREIGN KEY(`zipId`) REFERENCES zips(ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
FOREIGN KEY(`cityId`) REFERENCES cities(ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE

);

//cityState
CREATE  TABLE IF NOT EXISTS `storefront`.`cityState`(
ID INT NOT NULL CHECK(ID > 0),
stateId INT NOT NULL CHECK(ID > 0),
cityId INT NOT NULL CHECK(ID > 0),
PRIMARY KEY(ID),
FOREIGN KEY(`stateId`) REFERENCES states(ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
FOREIGN KEY(`cityId`) REFERENCES cities(ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);