server:
  port: 8080
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/EAD-9?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  mvc:
   view:
    prefix: /WEB-INF/View/
    suffix: .jsp